/** Golden value paths use [] for array indices, following plan-import coverage. */
export const CLAIMED = [
  { path: "blockToStory[]", test: "primitive claims and live directional gaps" },
  { path: "blockToStory[].blockTitle", test: "primitive claims and live directional gaps" },
  { path: "blockToStory[].fixture", test: "primitive claims and live directional gaps" },
  { path: "blockToStory[].storyName", test: "primitive claims and live directional gaps" },
  { path: "conflicts[]", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].blocking", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].code", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].evidence[].pageNumber", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].evidence[].source", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.blocks[].blockTitle", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.blocks[].fixture", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.level", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.levelA", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.levelB", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.reference.fixture", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.reference.titles[]", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.referenceMm", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.series.fixture", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.series.titles[]", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.seriesMm", test: "primitive claims and live directional gaps" },
  { path: "conflicts[].payload.storyName", test: "primitive claims and live directional gaps" },
  { path: "grid.xLabels[]", test: "primitive claims and live directional gaps" },
  { path: "grid.xSpansMm[]", test: "primitive claims and live directional gaps" },
  { path: "grid.yLabels[]", test: "primitive claims and live directional gaps" },
  { path: "grid.ySpansMm[]", test: "primitive claims and live directional gaps" },
  { path: "pages[].blockTitles[]", test: "primitive claims and live directional gaps" },
  { path: "pages[].fixture", test: "primitive claims and live directional gaps" },
  { path: "pages[].listKinds[]", test: "primitive claims and live directional gaps" },
  { path: "pages[].pageNumber", test: "primitive claims and live directional gaps" },
  { path: "pages[].roles[]", test: "primitive claims and live directional gaps" },
  { path: "pages[].source", test: "primitive claims and live directional gaps" },
  { path: "stories.heightsMm[]", test: "primitive claims and live directional gaps" },
  { path: "stories.levels[]", test: "primitive claims and live directional gaps" },
  { path: "storiesReference.fixture", test: "primitive claims and live directional gaps" },
  { path: "storiesReference.titles[]", test: "primitive claims and live directional gaps" },
  { path: "unmatchedBlocks[]", test: "primitive claims and live directional gaps" },
  { path: "unmatchedBlocks[].blockTitle", test: "primitive claims and live directional gaps" },
  { path: "unmatchedBlocks[].fixture", test: "primitive claims and live directional gaps" },
] as const

export const REFERENCE_ONLY = [
  { path: "$comment", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "knownGaps[].direction", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "knownGaps[].path", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "knownGaps[].reason", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "knownGaps[].ref", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "pages[].frameCount", reason: "Human frame count is not a parser series count." },
  { path: "set", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "unsure[].path", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
  { path: "unsure[].reason", reason: "Source identity, transcription commentary, or gap/uncertainty metadata; not a parser output claim." },
] as const
